#!/usr/bin/env python3
"""
Odds-API.io FanDuel MLB Pitcher K Line Probe v4

Standalone diagnostic only. Does NOT modify api.py, predictions, records, or PropLine.

What this tests:
- Uses Odds-API.io v3
- sport=baseball, league=usa-mlb
- bookmaker=FanDuel for events
- bookmakers=FanDuel for odds/multi
- Searches the nested FanDuel Player Props payload for labels like:
    "Yoshinobu Yamamoto (Total Strikeouts)"
- Extracts player, line/hdp, over price, under price, event, status, and raw path

Env var required:
    ODDS_API_IO_KEY

Run:
    python odds_apiio_k_line_probe_v4.py --max-events 15
    python odds_apiio_k_line_probe_v4.py --max-events 15 --dump-raw-hits
"""

from __future__ import annotations

import argparse
import csv
import json
import os
import re
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Tuple

import requests

BASE = "https://api.odds-api.io/v3"
OUT_DIR = Path("/data/odds_provider_tests")
OUT_DIR.mkdir(parents=True, exist_ok=True)

KEY_ENV = "ODDS_API_IO_KEY"
SPORT = "baseball"
LEAGUE = "usa-mlb"
BOOK_EVENT_PARAM = "FanDuel"
BOOK_ODDS_PARAM = "FanDuel"


def mask_url(url: str) -> str:
    return re.sub(r"(apiKey=)[^&]+", r"\1***", url)


def shape(x: Any) -> Dict[str, Any]:
    if isinstance(x, list):
        d = {"type": "list", "len": len(x)}
        if x:
            d["first_type"] = type(x[0]).__name__
            if isinstance(x[0], dict):
                d["first_keys"] = list(x[0].keys())[:12]
        return d
    if isinstance(x, dict):
        return {"type": "dict", "len": len(x), "first_keys": list(x.keys())[:12]}
    return {"type": type(x).__name__}


def get_json(url: str, params: Dict[str, Any], requests_log: List[Dict[str, Any]], label: str) -> Tuple[int, Any, str]:
    try:
        r = requests.get(url, params=params, timeout=30)
        text = r.text[:2000]
        try:
            payload = r.json()
        except Exception:
            payload = {"_non_json_text_preview": text}
        requests_log.append({
            "label": label,
            "status_code": r.status_code,
            "url": mask_url(r.url),
            "shape": shape(payload),
            "error_preview": payload if (r.status_code >= 400 and isinstance(payload, dict)) else None,
        })
        return r.status_code, payload, r.url
    except Exception as e:
        requests_log.append({"label": label, "status_code": None, "url": url, "error": repr(e)})
        return 0, {"error": repr(e)}, url


def is_pending_or_future(ev: Dict[str, Any]) -> bool:
    status = str(ev.get("status") or "").lower()
    if status in {"pending", "scheduled", "pre-game", "pregame", "preview", "not_started", "not started"}:
        return True
    # If status is missing/odd, use date as a fallback.
    date_s = ev.get("date") or ev.get("startTime") or ev.get("start_time")
    if isinstance(date_s, str):
        try:
            ds = date_s.replace("Z", "+00:00")
            dt = datetime.fromisoformat(ds)
            if dt.tzinfo is None:
                dt = dt.replace(tzinfo=timezone.utc)
            return dt >= datetime.now(timezone.utc)
        except Exception:
            pass
    return False


def chunks(xs: List[Any], n: int) -> Iterable[List[Any]]:
    for i in range(0, len(xs), n):
        yield xs[i:i+n]


def walk(obj: Any, path: str = "") -> Iterable[Tuple[str, Any]]:
    yield path, obj
    if isinstance(obj, dict):
        for k, v in obj.items():
            child = f"{path}.{k}" if path else str(k)
            yield from walk(v, child)
    elif isinstance(obj, list):
        for i, v in enumerate(obj):
            child = f"{path}[{i}]"
            yield from walk(v, child)


def find_parent_by_path(root: Any, path: str) -> Optional[Any]:
    """Simple path evaluator for paths generated by walk, enough for debug extraction."""
    cur = root
    # split on dots but keep [idx]
    parts: List[str] = []
    for part in path.split('.') if path else []:
        parts.append(part)
    for part in parts[:-1]:
        # key may include [idx] chain
        m = re.match(r"([^\[]+)((?:\[\d+\])*)$", part)
        if not m:
            return None
        key = m.group(1)
        idxs = re.findall(r"\[(\d+)\]", m.group(2))
        if isinstance(cur, dict):
            cur = cur.get(key)
        else:
            return None
        for idx_s in idxs:
            if isinstance(cur, list):
                idx = int(idx_s)
                if idx >= len(cur):
                    return None
                cur = cur[idx]
            else:
                return None
    return cur


def parse_player_from_label(label: str) -> str:
    # "Yoshinobu Yamamoto (Total Strikeouts)" -> "Yoshinobu Yamamoto"
    return re.sub(r"\s*\([^)]*strikeout[^)]*\)\s*$", "", label, flags=re.I).strip()


def as_float(x: Any) -> Optional[float]:
    if x is None:
        return None
    try:
        return float(x)
    except Exception:
        try:
            return float(str(x).replace("+", "").strip())
        except Exception:
            return None


def extract_price(row: Dict[str, Any], keys: List[str]) -> Optional[Any]:
    for k in keys:
        if k in row and row.get(k) not in (None, ""):
            return row.get(k)
    return None


def extract_line(row: Dict[str, Any]) -> Optional[float]:
    for k in ["hdp", "line", "point", "points", "handicap", "total", "value"]:
        val = as_float(row.get(k))
        if val is not None:
            return val
    # Sometimes a line is embedded in a label: "Over 5.5" etc.
    label = str(row.get("label") or row.get("name") or "")
    m = re.search(r"(?:over|under|o|u)\s*([0-9]+(?:\.5)?)", label, flags=re.I)
    if m:
        return as_float(m.group(1))
    return None


def event_name(ev: Dict[str, Any]) -> str:
    away = ev.get("away") or ev.get("awayTeam") or ev.get("away_team") or ""
    home = ev.get("home") or ev.get("homeTeam") or ev.get("home_team") or ""
    if away or home:
        return f"{away} @ {home}".strip(" @")
    return str(ev.get("name") or ev.get("event") or ev.get("id") or "")


def extract_k_lines_from_event(ev: Dict[str, Any], dump_raw_hits: bool = False) -> Tuple[List[Dict[str, Any]], List[Dict[str, Any]], Dict[str, int]]:
    rows: List[Dict[str, Any]] = []
    raw_hits: List[Dict[str, Any]] = []
    market_names: Dict[str, int] = {}

    ev_id = ev.get("id")
    ev_name = event_name(ev)
    ev_date = ev.get("date")
    ev_status = ev.get("status")

    # Count market-ish names for diagnosis.
    for p, node in walk(ev):
        if isinstance(node, dict):
            nm = node.get("name") or node.get("market") or node.get("marketName") or node.get("label")
            if isinstance(nm, str) and any(token in p.lower() for token in ["bookmaker", "market", "odds"]):
                if len(nm) < 80:
                    market_names[nm] = market_names.get(nm, 0) + 1

    # Main extraction: find dict rows whose label/name mentions Total Strikeouts or strikeouts.
    for p, node in walk(ev):
        if not isinstance(node, dict):
            continue
        label = str(node.get("label") or node.get("name") or node.get("title") or "")
        blob = json.dumps(node, ensure_ascii=False)[:2000]
        if not re.search(r"strikeout", label + " " + blob, flags=re.I):
            continue
        # Stronger filter to avoid general game/team strings if possible.
        if not re.search(r"total\s+strikeouts|pitcher\s+strikeouts|strikeouts", label + " " + blob, flags=re.I):
            continue

        line = extract_line(node)
        player = parse_player_from_label(label) if label else ""
        over = extract_price(node, ["over", "Over", "o", "priceOver", "overPrice", "over_price"])
        under = extract_price(node, ["under", "Under", "u", "priceUnder", "underPrice", "under_price"])

        # If this dict is a container and not a row, skip unless it has usable line/label.
        if not label and line is None:
            continue

        row = {
            "provider": "odds-api.io",
            "book": "FanDuel",
            "event_id": ev_id,
            "event": ev_name,
            "event_date": ev_date,
            "event_status": ev_status,
            "player": player,
            "label": label,
            "line": line,
            "over_price": over,
            "under_price": under,
            "path": p,
            "raw_keys": list(node.keys()),
        }
        rows.append(row)
        if dump_raw_hits:
            raw_hits.append({"path": p, "raw": node})

    # De-dupe rows: same event/player/line/label/path enough.
    seen = set()
    deduped: List[Dict[str, Any]] = []
    for r in rows:
        key = (r.get("event_id"), r.get("player"), r.get("label"), r.get("line"), r.get("over_price"), r.get("under_price"))
        if key in seen:
            continue
        seen.add(key)
        deduped.append(r)
    return deduped, raw_hits, market_names


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--max-events", type=int, default=15)
    ap.add_argument("--batch-size", type=int, default=10)
    ap.add_argument("--dump-raw-hits", action="store_true")
    args = ap.parse_args()

    key = os.getenv(KEY_ENV, "").strip()
    generated = datetime.now(timezone.utc).isoformat()
    requests_log: List[Dict[str, Any]] = []
    notes: List[str] = []
    error: Optional[str] = None

    if not key:
        error = f"Missing {KEY_ENV}"
        print(error)
        return 2

    # 1) Events
    status, events_payload, _ = get_json(
        f"{BASE}/events",
        {"sport": SPORT, "league": LEAGUE, "bookmaker": BOOK_EVENT_PARAM, "apiKey": key},
        requests_log,
        "events",
    )
    if status != 200 or not isinstance(events_payload, list):
        error = "Events request failed or was not a list."
        events: List[Dict[str, Any]] = []
    else:
        events = [ev for ev in events_payload if isinstance(ev, dict)]

    pending_events = [ev for ev in events if is_pending_or_future(ev)]
    used_events = pending_events[:args.max_events]
    ids = [str(ev.get("id")) for ev in used_events if ev.get("id") is not None]

    # 2) Odds multi
    odds_payloads: List[Dict[str, Any]] = []
    if not ids and not error:
        error = "No pending/future events had IDs."
    for batch in chunks(ids, max(1, min(10, args.batch_size))):
        st, payload, _ = get_json(
            f"{BASE}/odds/multi",
            {"eventIds": ",".join(batch), "bookmakers": BOOK_ODDS_PARAM, "apiKey": key},
            requests_log,
            "odds/multi",
        )
        if st != 200:
            notes.append(f"odds/multi failed for batch {batch}: status {st}")
            continue
        if isinstance(payload, list):
            odds_payloads.extend([x for x in payload if isinstance(x, dict)])
        elif isinstance(payload, dict):
            # Some APIs wrap list responses.
            for k in ["data", "events", "results", "odds"]:
                if isinstance(payload.get(k), list):
                    odds_payloads.extend([x for x in payload[k] if isinstance(x, dict)])
                    break

    # 3) Extract rows
    all_rows: List[Dict[str, Any]] = []
    all_raw_hits: List[Dict[str, Any]] = []
    market_counts: Dict[str, int] = {}
    for ev in odds_payloads:
        rows, raw_hits, mc = extract_k_lines_from_event(ev, dump_raw_hits=args.dump_raw_hits)
        all_rows.extend(rows)
        all_raw_hits.extend(raw_hits)
        for k, v in mc.items():
            market_counts[k] = market_counts.get(k, 0) + v

    # De-dupe final rows.
    seen = set()
    k_lines: List[Dict[str, Any]] = []
    for r in all_rows:
        key2 = (r.get("event_id"), r.get("player"), r.get("line"), r.get("over_price"), r.get("under_price"), r.get("label"))
        if key2 in seen:
            continue
        seen.add(key2)
        k_lines.append(r)

    out = {
        "probe_version": "odds_apiio_k_line_probe_v4_nested_player_props",
        "generated_at_utc": generated,
        "target": "FanDuel main MLB pitcher strikeouts line",
        "has_key": bool(key),
        "sport": SPORT,
        "league": LEAGUE,
        "bookmaker": BOOK_ODDS_PARAM,
        "request_count": len(requests_log),
        "events_total": len(events),
        "pending_or_future_events": len(pending_events),
        "events_used": len(used_events),
        "odds_payload_count": len(odds_payloads),
        "k_lines_count": len(k_lines),
        "k_lines": k_lines,
        "market_names_seen": dict(sorted(market_counts.items(), key=lambda kv: (-kv[1], kv[0]))[:100]),
        "raw_hits_sample": all_raw_hits[:20],
        "requests": requests_log,
        "notes": notes,
        "error": error,
    }

    json_path = OUT_DIR / "odds_apiio_k_line_probe_v4_latest.json"
    csv_path = OUT_DIR / "odds_apiio_k_line_probe_v4_latest.csv"
    json_path.write_text(json.dumps(out, indent=2, ensure_ascii=False), encoding="utf-8")

    with csv_path.open("w", newline="", encoding="utf-8") as f:
        fields = ["event_date", "event", "event_status", "player", "line", "over_price", "under_price", "label", "path"]
        w = csv.DictWriter(f, fieldnames=fields)
        w.writeheader()
        for r in k_lines:
            w.writerow({k: r.get(k) for k in fields})

    print("=== ODDS-API.IO K LINE PROBE V4 ===")
    print(f"Generated UTC: {generated}")
    print("Target: FanDuel main MLB pitcher strikeouts line")
    print(f"has_key={bool(key)} sport={SPORT} league={LEAGUE} bookmaker={BOOK_ODDS_PARAM}")
    print(f"request_count={len(requests_log)} events_total={len(events)} pending_or_future={len(pending_events)} events_used={len(used_events)} odds_payload_count={len(odds_payloads)} k_lines_count={len(k_lines)}")
    if error:
        print(f"ERROR: {error}")
    print("\nEVENTS USED")
    for ev in used_events[:12]:
        print(f"- {ev.get('id')} | {event_name(ev)} | {ev.get('date')} | {ev.get('status')}")
    print("\nMARKET NAMES SEEN")
    if market_counts:
        for name, cnt in sorted(market_counts.items(), key=lambda kv: (-kv[1], kv[0]))[:30]:
            print(f"- {name}: {cnt}")
    else:
        print("None detected")
    print("\nSAMPLE K LINES")
    if k_lines:
        for r in k_lines[:30]:
            print(f"- {r.get('player')} | line={r.get('line')} | over={r.get('over_price')} | under={r.get('under_price')} | {r.get('event')} | {r.get('label')} | path={r.get('path')}")
    else:
        print("No K lines found.")
    if args.dump_raw_hits:
        print("\nRAW HIT SAMPLE")
        for h in all_raw_hits[:10]:
            print(f"PATH {h.get('path')}: {json.dumps(h.get('raw'), ensure_ascii=False)[:1000]}")
    print("\nREQUESTS")
    for req in requests_log:
        print(f"- {req.get('status_code')} {req.get('label')} shape={req.get('shape')} url={req.get('url')}")
        if req.get("error_preview"):
            print(f"  error_preview={req.get('error_preview')}")
    print("\nOUTPUTS")
    print(json_path)
    print(csv_path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
