"""NHL count-model viewer: genuine V2-only website contract, never legacy unders."""
import json
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
PAGE = ROOT / "docs" / "nhl.html"
DATA = ROOT / "docs" / "nhl_v2_shadow.json"


def test_page_mirrors_nfl_projections_without_fixed_line_betting_calls():
    html = PAGE.read_text(encoding="utf-8")
    for field in ('"mean"', '"median"', '"sd"', '"p10"', '"p90"', '"p_ge3"',
                  '"p0"', 'T24H', 'T90', 'T30', 'id="player"', 'id="date"',
                  'id="team"', 'id="game"', 'NOT CERTIFIED',
                  'historical_corrected_probabilities_were_not_published_pregame'):
        assert field in html
    assert 'fetch("nhl_v2_shadow.json"' in html
    assert 'fetch("nhl_predictions.json"' not in html
    assert 'official betting picks' in html.lower()


def test_navigation_exists_from_nfl_and_main_site():
    for p in (ROOT/"docs"/"index.html", ROOT/"docs"/"nfl.html"):
        assert 'href="nhl.html"' in p.read_text(encoding="utf-8")


def test_no_unverified_shots_are_passed_as_live_official_bets():
    if not DATA.exists():
        pytest.skip("Website snapshot not yet generated by verified V2 Actions bridge")
    d = json.loads(DATA.read_text())
    assert d["schema"] == "nhl-v2-sog-nfl-style-shadow-v1"
    assert d["status"] == "RESEARCH_ONLY_NOT_VALIDATED_FOR_BETTING"
    assert d["not_a_betting_board"] is True
    assert d["actual_player_book_lines_verified"] is False
    assert d["dressed_lineups_verified"] is False
    assert d["verified_original_hash_chain"] is True
    assert d["verified_frozen_code_and_model_lock"] is True
    assert d["historical_corrected_probabilities_were_not_published_pregame"] is True
    assert len(d["source_snapshot_commit_sha"]) == 40
    assert len(d["source_ledger_sha256"]) == 64
    assert d["total_valid_forecasts"] == sum(len(v) for v in d["forecasts"].values())
    assert "pick" not in d["row_fields"] and "line" not in d["row_fields"]
    assert len(d["dates"]) > 0
    assert all(r[d["row_fields"].index("p_ge1")] >= r[d["row_fields"].index("p_ge3")]
               for rows in d["forecasts"].values() for r in rows)
